/* definitions generated by preprocessor, copy into defines.h */		
#ifndef	PPINC	
#define	_ATMEGA16	// device select: _ATMEGAxxxx
#define	_B1024	// boot size select: _Bxxxx (words), powers of two only
//#include	"iom16.h"	
		
/* define pin for enter-self-prog-mode */		
#define	PROGPORT	PORTA
#define	PROGPIN	PINA
#define	PROG_NO	PA0
		
/* baud rate register value calculation */		
#define	CPU_FREQ	16000000
#define	BAUD_RATE	19200
#define	BRREG_VALUE	51
		
/* definitions for UART control */		
#define	BAUD_RATE_LOW_REG	UBRRL
#define	UART_CONTROL_REG	UCSRB
#define	ENABLE_TRANSMITTER_BIT	TXEN
#define	ENABLE_RECEIVER_BIT	RXEN
#define	UART_STATUS_REG	UCSRA
#define	TRANSMIT_COMPLETE_BIT	TXC
#define	RECEIVE_COMPLETE_BIT	RXC
#define	UART_DATA_REG	UDR
		
/* definitions for SPM control */		
#define	SPMCR_REG	SPMCR
#define	PAGESIZE	128
#define	APP_END	14336
//#define	LARGE_MEMORY	
		
/* definitions for device recognition */		
#define	PARTCODE	0x75
#define	SIGNATURE_BYTE_1	0x1E
#define	SIGNATURE_BYTE_2	0x94
#define	SIGNATURE_BYTE_3	0x03
		
/* indicate that preprocessor result is included */		
#define	PPINC	
#endif		
