//==============================================================================
// File:           aeskeys.h
// Compiler:       IAR Atmel AVR C/EC++ Compiler
// Output Size:    32
// Created:        Mon Apr 03 23:49:58 2023

//
// Description:    This file is generated by 'create' tool and is to be included
//                 in the 'bootldr' project. It contains a AES key table for
//                 a proper decryption of the file encrypted using the same
//                 configurations.
//
// Keys used:      KEY1 = B60BF641F6C8403F308ED41571D9393DC765
//                 KEY2 = F728B4AA4B50C6F61C
//                 KEY3 = 2A193C2497021948F7
//==============================================================================


const unsigned char kTable[32] = 
{
	0xb6, 0x17, 0xd9, 0x0f, 0x6c, 0x08, 0x0f, 0x98,
	0x8e, 0xa8, 0x55, 0x8e, 0x93, 0x27, 0x71, 0xb2,

	0xf7, 0x51, 0xd2, 0x52, 0xb5, 0x18, 0xbd, 0x0e,

	0x2a, 0x32, 0xf0, 0x24, 0x70, 0x43, 0x52, 0x7b,
};
